language: node_js
sudo: false
node_js:
- '5.1'
addons:
  code_climate:
    repo_token: a346754071423801ffb9ee6ed15557e835cd0341eb452542410cc11bcd052adf
env:
  global:
  - AWS_ACCESS_KEY_ID: AKIAJH2D5IPIRHYJT5IA
  - AWS_SECRET_ACCESS_KEY: zV0MFtPq5DYJbs8fd4gk7rdDhxPEeDgvVlv+JrRG8YwUU0ib+sj+D1wV2MXGKdUs35mjH3wahirdL3Uxoo9K32BuL7WK3RXPbLUzc2Ed9+HHor7Se/rMN4dif85/DU2iI0vxtCkmgjzxtyIWwXPeNkqam6EW0GLYJA70YmN2a7vlPkK08ua2Lz1Ndv4bYB/au5BX2bT0PN264YyBE7pwCctO2FZ+mpV1YWhHukNU9N1wvfn0t6vDPaOG6zSxU+SaNcmv5chlw78PFm/T650yU9xnUD7cWCcCgfl1j+7poTb/bqsAAQhAqRHqop5ft477nUVNp51js+T0t1XH/bGbxgY0/QhiCMEY58cAd1kG3xV5ivxvs5AyNRHC/or+r3M88G4t8SA7OGSkG/6Ksm9ekEPK+0q+l6XlCM7exTyaQiI65pE4y7UOkMgFrIeM0Ltte007tKpT65w9vonY2tIiicb266JqQdPEotWUp5GsYLa03GMVuc6D6mO88uMPj4URwSuiPCgeEFCda0P0bdBsar9FeiDFuIk8T1z1MWhKYee6KmEdRo8kZdjzmRR/g3H1HebePlfjpA/3MW6giwB0ZUH9zf8xzyNA6mX1kbOgJw+wpCiU6mfBbStmx3FUzum3e5U2/xw7OVZGRW5NDABn43WtELADfPo9U0KW/8a1wyI=
before_script:
- if [ ${TRAVIS_BRANCH} == master ]; then export NODE_ENV=production; else export
  NODE_ENV=staging; fi
after_success:
- npm install --global webpack
- NODE_ENV=production webpack --config webpack.config.prod.js
- mkdir build
- cp -r index.html cwc dist build/
- for file in `find build -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- ./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH
deploy:
  provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: c4AAOq1v934Bxlihi46UaXCahPvMLBRZs6QliWxBl0uU3JWnlKgmu7H6uW5BrGXvmNV5rjXe72byutSzbF/LaSuE4B6MgrqdGsDBNWd/gnYFf7zFhCB30FAu8qmQb1JPO8ulteLydzTSupJmqRwhykQjsRdiIQRJDETBcyxD8jnkopy6Di/UmWzMG2v4pGAlelBc0AfEM3AcuoTxUrcG/GEPT8IMHDV4286CVGndaV5qda3phpOSZybvNaF8uT/okut7IS/J68iXytLHbE1IVGGvfp4gT4eEi5EtwWbyeCOObCJU13atN3g+w+T65hQCWpPFVFNYh+ICYayN0RVSii5Tjy7vwBaqgUadJtVgxy2sqcx7UwRCuwAYsIbUZQvRQCuAkfN0mNLopf7sHzRjzuyROOlCO8zDM+C3carNBO3GN4Hce1c3kA7pIzcGDS02iu4fRXjxdJnXIoluJQFrICbke4LAPWx7rEDWOdXuYZcfGM9CR4EUcI5BfSpvmYjPuBm5zzEPK3jO5x4cbfZJQrD3rhr81e0qRspZHwk0GkI0c4U+1DZKVK/Oa220ISrfoOjyJXJHMFnRaqk7WNyZglubBLGoy6n6g1lB99HvyGmfC6ANhgJuu/40bYJcLqX5jo5BUQB37/6ONX32VK1ytOC2CnlKsWoujDpTRGGEEr0=
  bucket: store.octoblu.com
  local_dir: build
  skip_cleanup: true
  endpoint: store.octoblu.com.s3-website-us-west-2.amazonaws.com
  detect_encoding: true
  region: us-west-2
  on:
    tags: true
