export const FETCH_BLUPRINTS               = 'FETCH_BLUPRINTS'
export const FETCH_BLUPRINTS_BY_COLLECTION = 'FETCH_BLUPRINTS_BY_COLLECTION'
export const FETCH_BLUPRINTS_BY_TAG_NAME   = 'FETCH_BLUPRINTS_BY_TAG_NAME'

export const FETCH_COLLECTIONS             = 'FETCH_COLLECTIONS'
