export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS'
export const FETCH_BLUPRINT    = 'FETCH_BLUPRINT'
export const FETCH_BLUPRINTS   = 'FETCH_BLUPRINTS'
export const SELECT_BLUPRINT   = 'SELECT_BLUPRINT'
